version: "3.8"

services:
  laravel:
    build:
      context: ./laravel
    depends_on:
      - mysql
    volumes:
      - ./laravel:/var/www/html
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - laravel

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password

  random_http:
    build:
      context: ./random_http
    ports:
      - "8080:80"
