services:
  laravel:
    image: laravel_alpine_image
    build:
      context: ./laravel
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    volumes:
      - ./laravel:/var/www/html
    command: sh -c "php artisan migrate --seed || php artisan migrate:fresh --seed && php-fpm"

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: laravel_db

  random_http:
    image: khaosdoctor/http-random-api-exporter:latest
    ports:
      - "8080:80"
